### ISSUE TITLE
Specification of FenceTSO

### ISSUE THREAD

**Issue by pratapsingh1729** [daniellustig/riscv-memory-model#1]
https://github.com/daniellustig/riscv-memory-model/blob/908654468f0603246eecf222b44af12b4b4ea4f3/riscv.als#L137

```
fun ppo_fence : MemoryEvent->MemoryEvent {
    (Load  <: ^po :> FencePRSR).(^po :> Load)
  + (Load  <: ^po :> FencePRSW).(^po :> Store)
  + (Store <: ^po :> FencePWSR).(^po :> Load)
  + (Store <: ^po :> FencePWSW).(^po :> Store)
  + (Load  <: ^po :> FenceTSO) .(^po :> MemoryEvent)
  + (Store <: ^po :> FenceTSO) .(^po :> Store)
}
```

In the last line, why do we not have:
```
(Store <: ^po :> FenceTSO) .(^po :> MemoryEvent)
```

Based on my reading of the RISC-V weak memory model specification, I think the `FenceTSO` instruction should force explicit synchronization between a store and any memory event. From the section on "Preserved Program Order" ([chapter 14](https://riscv.org/technical/specifications/)):

> The complete definition of preserved program order is as follows (and note that AMOs are simultaneously both loads and stores): memory operation a precedes memory operation b in preserved program order (and hence also in the global memory order) if a precedes b in program order, a and b both access regular main memory (rather than I/O regions), and any of the following hold:
[...]
> 4. There is a FENCE instruction that orders a before b

I have some examples for which alloy finds an instance with the current specification, but fails to do so when `Store` is changed to `MemoryEvent` as discussed.

**Comment by daniellustig** [comment]
Hi @pratapsingh1729,

Store-to-load ordering is the one type of ordering that fence.tso relaxes.  Fence.tso enforces the other three combinations (Load->Load, Load->Store, Store->Store).  The `(Load  <: ^po :> FenceTSO) .(^po :> MemoryEvent)` line captures the first two together, but adding `(Store <: ^po :> FenceTSO) .(^po :> MemoryEvent)` would pull in Store->Load ordering, which we don't want.

Can you maybe say a little more about what issue you're seeing exactly?  The riscv-semantics issue you linked to seems to show a discrepancy related to `fence rw,rw` rather than `fence.tso`, if I'm skimming that table right.

**Comment by pratapsingh1729** [comment]
@daniellustig Thanks very much for the response! This actually was a bug on our end---we were mistakenly using `FenceTSO` in our calls to Alloy when instead we should have been using `Fence.pr.pw.sr.sw`. The rest of our system was implementing a full fence, so when I make this change we get the expected behavior. Apologies for the confusion and thanks for providing this model!
